spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: ${MYSQL_URL}
#    url: jdbc:mysql://localhost:3306/student?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSI=false
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}

#spring:
#  datasource:
#    url: ${JDBC_DATASOURCE_URL}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


