#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/student?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSI=false
#    username: root
#    password: samsu

spring:
  datasource:
    url: ${JDBC_DATASOURCE_URL}
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


