spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSI=false
    username: root
    password: samsu

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


